### ISSUE TITLE
I can't change the  labels of buttons

### ISSUE THREAD

**Issue by rahman-jn** [srdjan/react-multistep#102]
I'm going to use this package in a website built in Farsi language but I didn't find any props to change the buttons labels.
In addition I want to change buttons positions but divisions which contain buttons don't have any class name.
 It restricts the flexibility of using package.

**Comment by srdjan** [comment]
Hi @rahman-jn !
there are few options for solution to your request:
- [ ] I could add full support for internalization to the component (seems not much, only two words are exposed, but reluctant to add it at this time)
- [ ] you are welcome to open a PR and help
- [ ] you can vendor this library and change it locally, it is only one file  and you would have two changes (line 205 & 209):
<img width="616" alt="Screenshot 2023-01-27 at 5 32 32 PM" src="https://user-images.githubusercontent.com/61190/215273950-f6f0a6d4-cab9-4753-bae4-74f00560cfa5.png">

**Comment by rahman-jn** [comment]
Thanks @srdjan .
It sounds the perfect solution.
I'll test it
