### ISSUE TITLE
Can't build example

### ISSUE THREAD

**Issue by FrancoisSoler** [srdjan/react-multistep#108]
Hi,

I've wanted to give a try to this packages, so I followed the instructions to install the example, so I've been able to clone the repo, npm install and then cd exemple I do Npm install, npm run build but it stops with this error 

`npm run build

> react-multistep-example@1.2.0 build
> esbuild app.js --bundle --format=cjs --outfile=./bundle.js --loader:.js=jsx

✘ [ERROR] Could not resolve "Multistep"

    app.js:3:22:
      3 │ import MultiStep from 'Multistep'
        ╵                       ~~~~~~~~~~~

  You can mark the path "Multistep" as external to exclude it from the bundle,
  which will remove this error.

1 error

`
I have tried a few things but none of them worked, any idea ?

**Comment by srdjan** [comment]
thanks for reporting!
did you run 'npm run build in the root folder first? (this builds the component, 'Step 2' in readme file)

**Comment by srdjan** [comment]
I think the problem may be in the order of instruction steps, build step for the ReactMultistep component tries to copy it's build to the ./example/node_modules - but that folder doesn't exist yet.  
Can you try this, please (if confirmed, I'll fix the build script this weekend):

Start by cloning the repo locally:
//--step 1
```
git clone https://github.com/srdjan/react-multistep.git   // clone the repo
cd react-multistep/example                                // navigate to the example folder
npm install                                               // install  dependancies for the example
```

Next, navigate back to the root folder, install dependencies and build the ReactMultistep component:
```
cd ..                                                     // navigate to the root folder
npm install
npm run build 
```

On a successful ReactMultistep component build, navigate to the example folder and try it:
```
cd example
npm run build
npm start
```


Now you can try to open the example in your favorite browser. Let me know - thanks!

**Comment by TeteDeCom** [comment]
Thanks for the fast reply,

It works now !
