### ISSUE TITLE
Steps in same color

### ISSUE THREAD

**Issue by guilherme-funchal** [srdjan/react-multistep#112]
Hello, I'm trying to test the example but all Steps colors stay in same color(Gray) and the Code seens doesn't seem right.

`<ol class="go2392553372 go169520481"><li class="go2150698616 go433304200" value="0" style="transform: rotate(0deg);"><span>Step 1</span></li><li class="go2150698616 go433304200" value="1" style="transform: rotate(0deg);"><span>Step 2</span></li><li class="go2150698616 go3842760039" value="2" style="transform: rotate(0deg);"><span>Step 3</span></li><li class="go2150698616 go2335061104" value="3" style="transform: rotate(0deg);"><span>Step 4</span></li></ol>`

**Comment by srdjan** [comment]
can you share the a bit of code that shows how are you trying to change the default color?
I'm assuming you are using 
```
stepCustomStyle
```
prop ?
