### ISSUE TITLE
Button text based on step

### ISSUE THREAD

**Issue by Github743** [srdjan/react-multistep#113]
I want to change the button text dynamically based on the step I am on how to do that

**Comment by srdjan** [comment]
here is the part of docs that explains that:
https://github.com/srdjan/react-multistep#-new-you-can-also-use-style-props-for-the-navigation-buttons-and-change-how-they-look 
I can see that docs for this are not clear and I'll fix that, meantime, here is an example app you can try:

```
import React from 'react'
import ReactDOM from 'react-dom'
import MultiStep from 'react-multistep'
import StepOne from './stepOne'
import StepTwo from './stepTwo'
import StepThree from './stepThree'
import StepFour from './stepFour'

const App = () => (
  <div className='container'>
    <MultiStep activeStep={0} prevButton={{title: 'Before','style:{ background: 'red' }, title: 'Order Workflow'}} >
      <StepOne title='Step 1'/>
      <StepTwo title='Step 2'/>
      <StepThree title='Step 3'/>
      <StepFour title='Step 4'/>
    </MultiStep>
    <div className='app-footer'>
      <h6>Use navigation buttons or click on progress bar for next step.</h6>
      Code is on{' '}
      <a href='https://github.com/Srdjan/react-multistep' target='_blank' rel='noreferrer'>
        github
      </a>
    </div>
  </div>
)

ReactDOM.render(<App />,   ##document.getElementById('root'))
```

So, because of this line:
```
    <MultiStep activeStep={0} prevButton={{title: 'Before','style:{ background: 'red' }, title: 
```

Previous button will have 'red' background and text will say: 'Before'

**Comment by Github743** [comment]
Here is the code 

https://codesandbox.io/s/59gqjg

If you check the last step continue was disabled where I need to button text to be submit and enabled

**Comment by srdjan** [comment]
I see... Sorry, I misunderstood your issue, although it was clearly stated :)
This is not supported at the moment, I'll take a look over the weekend and possibly add it...

**Comment by Github743** [comment]
> I see... Sorry, I misunderstood your issue, although it was clearly stated :) This is not supported at the moment, I'll take a look over the weekend and possibly add it...

Thank you

**Comment by Github743** [comment]
> I see... Sorry, I misunderstood your issue, although it was clearly stated :) This is not supported at the moment, I'll take a look over the weekend and possibly add it...

any luck on this?

**Comment by srdjan** [comment]
yes, there is some progress, will try to finish it next weekend, only time I can work on it :( 
should be able to close both this request & #110

**Comment by Github743** [comment]
> yes, there is some progress, will try to finish it next weekend, only time I can work on it :( should be able to close both this request & #110

No problem just waiting for the fix to be available

**Comment by srdjan** [comment]
ok, I have a working sample, you can see the demo here (and link to the code is below):

https://github.com/srdjan/react-multistep/assets/61190/88403b6d-59da-4ffc-b706-9d35b4497826

Unfortunately, while doing this< I realized that it is better for MultiStep to stay focused on its only concern: navigation and leave it to child components to execute their own logic/actions... 
What you want will still be possible, but MultiStep will only navigate and interact with child components only for validation purposes. Business logic Actions will be responsibility of child components. Also, navigation buttons appearance will change, to make it obvious that they are only for navigation.  I'll add the example once v6.0.0 progresses a little bit more. 

Alternatively, you could fork this pre-release and see if it works for your case better, but, just a warning, for my taste things are getting a bit too complicated with back and forth between the multistep and child components.
This branch commit where you can check the code:
https://github.com/srdjan/react-multistep/tree/140abe7ad946a6c9b32538248cbf2ebef4c92831

The code that enabled 'Submit' functionality, will be removed in the following commits

**Comment by Github743** [comment]
Thanks for the update, I will check and let you know

**Comment by srdjan** [comment]
also, see here how nav buttons will look like in v6, it should make it nicer when you have action/submit buttons on child components:

<img width="541" alt="Screenshot 2023-07-24 at 7 44 06 AM" src="https://github.com/srdjan/react-multistep/assets/61190/373c0fe0-c65e-46b7-9113-1780749c5ee7">

**Comment by Github743** [comment]
> also, see here how nav buttons will look like in v6, it should make it nicer when you have action/submit buttons on child components:
> 
> <img alt="Screenshot 2023-07-24 at 7 44 06 AM" width="541" src="https://user-images.githubusercontent.com/61190/255580120-373c0fe0-c65e-46b7-9113-1780749c5ee7.png">

Do you have fiddle for the same like stackblitz or other?

**Comment by srdjan** [comment]
no :(
you can just pull the v6 branch and run locally?

**Comment by srdjan** [comment]
just to make it clear, if you couldn't play with it, this is how the last step could look like with 'Submit' button anywhere inside your own child component...

<img width="555" alt="Screenshot 2023-07-29 at 10 10 36 AM" src="https://github.com/srdjan/react-multistep/assets/61190/019a2194-f2d5-4324-b480-c6bda049d00d">

**Comment by srdjan** [comment]
closing - but will reconsider improvements when v6 gets a little bit more complete
