### ISSUE TITLE
The local development errors

### ISSUE THREAD

**Issue by farshad-vgr** [srdjan/react-multistep#115]
I want to run this app locally but got these errors:
1- In the example directory when running 'npm start':
![one](https://github.com/srdjan/react-multistep/assets/53819019/6ffbe520-4f6c-4d53-865f-e6a97eccc01c)
Because there is no "react-multistep" in the dependencies. So I installed the "react-multistep" package and the above error is gone!

2- After that in the next try 'npm start':
![two](https://github.com/srdjan/react-multistep/assets/53819019/b2606bb6-a4b8-4868-b8dc-5bf5bb5a8e57)

Then in the local host browser "chrome Version 114.0.5735.199 (Official Build) (64-bit)" console shows:
![three](https://github.com/srdjan/react-multistep/assets/53819019/8aac4070-059b-457f-bb4d-938b1846230a)

Any idea to resolve these errors?!?!?!

**Comment by srdjan** [comment]
it seems that you missed a ```npm run build ``` step? 

```
cd ../example                 // (1) navigate to the example folder
npm install                   // (2) install dependencies
npm run build                 // (3) build the example
npm start                     // (4) start the local server
```

**Comment by farshad-vgr** [comment]
I did all the steps:

![er](https://github.com/srdjan/react-multistep/assets/53819019/84bbc675-934a-433b-8c2f-053d97a80323)

**Comment by farshad-vgr** [comment]
I think the problem happens when using the -f flag to copy contents. So I decided to do all steps manually. An error happens when using the cp command with the -f flag.

![flag](https://github.com/srdjan/react-multistep/assets/53819019/72ab95e1-feed-46fc-8157-a5d655739b3a)

And when replacing the -f with -Force, it works perfectly, and the app runs very well!

**Comment by srdjan** [comment]
Oh, I see... You are using powershell and copy command is different. 
Glad you found a workaround.

**Comment by filipecarneiro** [comment]
On windows, change `inst:comp` in `package.json` to `"inst:comp": "mkdir node_modules\\react-multistep && xcopy /Y /E ..\\build\\* node_modules\\react-multistep\\",`

**Comment by srdjan** [comment]
thanks, @filipecarneiro !
