### ISSUE TITLE
Port header rotation to v6.0.0-alpha

### ISSUE THREAD

**Issue by srdjan** [srdjan/react-multistep#117]
@ofirelarat,
I started to work on a new version, which will not be backwards compatible.
Main features are:
- headless (all styling coming from the hosting App)
- more flexible validation interaction with child components
- more 'modern' look for the top nav header, although, I may port original later or if demanded

It is not backwards compatible because I took opportunity to do the cleanup in preparation to focusing on more advanced navigation features (workflow like skip/jump to any step, etc)

I think that you have added top nav rotation feature at some point, and I would love if you can port it to v6.0.0 way :)

Branch is here:
https://github.com/srdjan/react-multistep/tree/v6.0.0-alpha

**Comment by ofirelarat** [comment]
I will check it out 👌

**Comment by ofirelarat** [comment]
Hey, I checked it
and its look like it is possible to get the rotate results without any code changing
because now all the styles coming from the host

example for rotated nav:
<img width="239" alt="image" src="https://github.com/srdjan/react-multistep/assets/17068656/cbbd3ae4-2b45-44ed-a494-9f04eecf5d0e">

So, now there is much more customizability of the styling, and with the right CSS properties you can get any view you would like.. 


This styles props made the rotation:
```
styles: {
    container: { 
      display: 'flex',
      padding: '5rem',
      marginTop: '5rem' 
    },
    topNav: {
      display: 'flex',
      flexDirection: 'column',
      margin: '0',
      paddingBottom: '2.2rem',
      listStyleType: 'none',
    },
    topNavStep: {
      color: 'silver',
      cursor: 'pointer',
      width: '25%',
      paddingTop: '4rem',
      paddingRight: '4rem',
      borderLeft: '1px solid silver'
    },
    todo: {
      color: 'gray',
    },
    doing: {
      color: '#1EAEDB',
    },
    done: {
      color: 'green',
    },
    skip: {
      color: 'silver',
    },
    prevButton: {
      display: 'none'
    },
    nextButton: {
      display: 'none'
    }
  }
```

**Comment by ofirelarat** [comment]
but I would suggest improving the default style, many time you would like to get some visualization in minimal time and some default values for the styles can help with this.

(Now as far as I tested, without styles properties the component will not work/nothing is visible)

**Comment by srdjan** [comment]
Agree, I will add the default styles back, just keeping that for the last moment. Will ping you when I have an approach to that. 

For heads up... What I want (need) is to add a more finer control of what next step is ( so it is not only sequential, but child components can be skipped). Also, want (need) to have option to treat child steps as server side pages, too. This two features should be optional, so that base use case doesn't change, but can be used if needed. With these features and adding back default styles - v6.x.x release will be feature complete.
