### ISSUE TITLE
Validation Issue

### ISSUE THREAD

**Issue by satishp04** [srdjan/react-multistep#123]
I attempted the provided example on the hosted link, and no validation errors are displayed when I click on "next," even though the email addresses do not match.
![Screenshot from 2024-03-13 12-31-15](https://github.com/srdjan/react-multistep/assets/107237227/ac14c867-049e-409e-aff5-368df8e7cdd9)

**Comment by srdjan** [comment]
this is just example of how the component is used, it is not providing a full application... But, you can take it, and customize to your needs.
