### ISSUE TITLE
Strange to have expect() calls in component def :)

### ISSUE THREAD

**Issue by winkler1** [Srdjan/react-multistep#2]
https://github.com/Srdjan/react-multistep/blob/master/src%2Fjs%2Fcomponents%2Fmultistep.js

**Comment by Srdjan** [comment]
I love it that way - tests are close to what they test - less context switching for me :)
these can be removed in the build/publish  step - but I prefer to leave them and let them run on target server too...

**Comment by winkler1** [comment]
Interesting :) Yeah, I do that too sometimes. Agree, it is handy. You could do the trick of checking production environment and stripping out for prod :)

**Comment by Srdjan** [comment]
yes :)

**Comment by Srdjan** [comment]
oh, just realized that you published it on react-rocks... cool, thanks !
