### ISSUE TITLE
Unable to load this module with WebPack

### ISSUE THREAD

**Issue by chuan137** [Srdjan/react-multistep#20]
bug? I use with `babel-loader` 6.2.4 and  `babel-preset-es2015` 6.9.0

```
node_modules/react-multistep/src/index.js Unexpected token (98:6)
You may need an appropriate loader to handle this file type.
```

**Comment by chuan137** [comment]
I see, it is due to index.js contains jsx code, but webpack does not automatically apply jsx loader for it.

**Comment by ciaoben** [comment]
@chuan137 I have also found this error. I have solved for now including this folder in my `webpack.config`, and changing the `.babelrc` of the package to one compatible with my installation. This way my webpack  parses the code like if its mine. 

Any better solution would be appreciated

**Comment by Srdjan** [comment]
I can only ask that if you guys find a solution to support both browserify and webpack - I'll gladly take the PR.
Otherwise, until I get more free time - browserify only, I'm afraid...

**Comment by rikkipitt** [comment]
@ciaoben Could you possibly elaborate on your workaround please? Would be great to get this working in my webpack project too!

**Comment by ciaoben** [comment]
@rikkipitt hey, it turned out to be a bad idea. Lot of problems emerged. I have ended up with my total custom solution... it is a pretty easy concept to integrate with react and it is always a less dependency 😃

**Comment by rikkipitt** [comment]
@ciaoben Since I asked you I rolled my own version too! Cheers anyway!

**Comment by Srdjan** [comment]
:+1:
