### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by ala85** [Srdjan/react-multistep#21]
Hi, I looked at the index.js and cannot see any validation included. How would you validate an individual step?

Any plan to integrate with Redux forms? Thanks.

**Comment by Srdjan** [comment]
Hi
validation is left out, this is just a component that allows navigation - you can add validation to your steps in any way you prefer

**Comment by tkrotoff** [comment]
Since the example features fields, would make sense to have validation in it

**Comment by srdjan** [comment]
agree, just don't have time (or direct need) right now... PR welcome, though :)
