### ISSUE TITLE
Error while compiling in webpack

### ISSUE THREAD

**Issue by debslab** [Srdjan/react-multistep#22]
I have imported the package and in while building in webpack, I am getting following error.
ERROR in ./~/react-multistep/src/index.js
Module parse failed: E:\work\webui\scm-hackfest\node_modules\react-multistep\src\index.js Unexpected token (98:6)
You may need an appropriate loader to handle this file type.
|   renderSteps() {
|     return this.props.steps.map((s, i)=> (
|       <li className={this.getClassName("progtrckr", i)} onClick={this.handleOn
Click} key={i} value={i}>
|         <em>{i+1}</em>
|         <span>{this.props.steps[i].name}</span>
 @ ./app/containers/TemplatePage/index.js 53:16-42
Child html-webpack-plugin for "index.html":

It says I don't have appropriate loader. Please let me know if I am missing something.

**Comment by Srdjan** [comment]
Hi there,
this package is set to work with browserify, and it doesn't support webpack
others have made it work with webpack, though, 
see https://github.com/Srdjan/react-multistep/issues/20
