### ISSUE TITLE
Not able to use the npm package - SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by younanjo** [Srdjan/react-multistep#23]
Trying to use your multistep plugin in my project and getting:

`ERROR in ./~/react-multistep/src/index.js
Module parse failed: /Users/demo/node_modules/react-multistep/src/index.js Unexpected token (98:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (98:6)
`

My .babelrc file looks like so:

`{
  "plugins": ["transform-react-jsx"],
  "presets": ["react", "es2015", "stage-2"],
  "env": {
    "development": {
      "presets": [ "react-hmre"]
    },
    "production": {
      "plugins": [
        "transform-react-constant-elements",
        "transform-react-remove-prop-types"
      ]
    }
  }
}
`

any idea what's going on?

**Comment by Srdjan** [comment]
seems that your project is using webpack, and this component is configured to use browserify...
see here: https://github.com/Srdjan/react-multistep/issues/20

**Comment by Srdjan** [comment]
I pushed changes that remove jsx from  the index.js file - simplest thing that could work - please pull the latest and try with your setup

**Comment by gnagel** [comment]
Hi @Srdjan 
The last commit [84799e8](https://github.com/Srdjan/react-multistep/commit/84799e8e1a65a07bb8cf2c9256d9b0f2ab3b939f) didn't include multistep.jsx.
Can you add multistep.jsx to the project?

Thx!
Glenn

**Comment by Srdjan** [comment]
:(
just did, sorry about that 
although the more I think about it - it may not change anything....
Let me know if you figure this out - thanks!

**Comment by Srdjan** [comment]
I have (wip) version with Webpack here: https://github.com/Srdjan/react-multistep-with-webpack...
