### ISSUE TITLE
var MultiStep = require('react-multistep').MultiStep; returns undefined

### ISSUE THREAD

**Issue by hossein761** [Srdjan/react-multistep#24]
'use strict';
var ReactDOM = require('react-dom');
var React = require('react');
var MultiStep = require('react-multistep').MultiStep;

//MultiStep is undefined
Could you please help?

**Comment by Srdjan** [comment]
this should work (as in example):
'use strict'
import React, { Component, PropTypes } from 'react'
import ReactDOM from 'react-dom'
import Multistep from '../../src/index.js'
import { steps } from './js/signup/index.js'

**Comment by sampathkatari** [comment]
Hey am also having the same issue..
Uncaught SyntaxError: Unexpected token import - index.js:2
file shown in the console as 
1. "use strict"
2. import MultiStep from './multistep'
3. 
4. export default MultiStep

In the example you mention to use
import Multistep from '../../src/index.js'
but here Multistep (where there is small s) but actual component you defined is MultiStep (S is capital) and when we are using in a application we cannot directly use this import that you mentioned in the example.

Can you please help on resolving this?
@hossein761 Was this problem resolved for you?

**Comment by Srdjan** [comment]
please check the latest,  
import Multistep from '../../src/index.js' 
is now: 
import Multistep from 'react-multistep'
this would work as long as you use 'npm link' to create local module
