### ISSUE TITLE
Last step: Next button not displayed except on click on navigation bar

### ISSUE THREAD

**Issue by alexisross** [Srdjan/react-multistep#25]
Hi,
When we are on the last step, the Next button is not there except when we click on the last step on the navigation.
![screenshot_1](https://cloud.githubusercontent.com/assets/17320998/20711156/819af0b6-b63e-11e6-9015-648414e50459.jpg)

**Comment by Srdjan** [comment]
hmm... that should be simple - I'll try to get to it over the weekend.
Thanks for reporting. If you happen to fix it - please send a PR

**Comment by alexisross** [comment]
The truth is I'm relatively new in NodeJs world and when I fork the project then try to build it its fails -_-
So in other time I would have helped you on this :)
Thanks anyway for your work.

**Comment by Srdjan** [comment]
no problem, if you can wait I'll fix over the weekend, just a super busy week right now...

**Comment by Srdjan** [comment]
fixed
