### ISSUE TITLE
Why this project is not a fork ? -> newbreedofgeek/react-stepzilla

### ISSUE THREAD

**Issue by alexisross** [Srdjan/react-multistep#26]
Hi,
I  found another project that is really like yours (and in the code there is similarity).
It's more advanced, but it's not a fork, why ?

**Comment by Srdjan** [comment]
ha! interesting, thanks for pointing out.
Of course that is fine, for a project like this, happy to share and happy that is used in anyway. 

 "Imitation is the sincerest form of flattery"

**Comment by Srdjan** [comment]
@newbreedofgeek cheers!
closing
