### ISSUE TITLE
Implement submit button

### ISSUE THREAD

**Issue by Dave-Algorism** [srdjan/react-multistep#27]
Thanks for this library. Please, how do one create a submit button after the completion of filling the form since only Prev and Next buttons are the ones available? And also how do one handle validations on each steps?

**Comment by srdjan** [comment]
@Dave-Algorism, you could add submit button inside your own component, same for validations...
Each component should handle it on its own. Off course, that doesn't cover all use cases, but application specific stuff is better kept out of generic component, like multi-step/wizzard
