### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by saroar** [srdjan/react-multistep#30]
ERROR in ./~/react-multistep/src/multistep.js
Module parse failed: /Developer/NullPay/TierraPay/client/node_modules/react-multistep/src/multistep.js Unexpected token (98:6)
You may need an appropriate loader to handle this file type.
|   renderSteps() {
|     return this.props.steps.map((s, i)=> (
|       <li className={this.getClassName("progtrckr", i)} onClick={this.handleOnClick} key={i} value={i}>
|         <em>{i+1}</em>
|         <span>{this.props.steps[i].name}</span>
 @ ./~/react-multistep/src/index.js 2:0-35
 @ ./app/bundles/WalletApp/components/SendMoney/SendMoney.jsx
 @ ./app/bundles/WalletApp/startup/registration.jsx
 @ multi es5-shim/es5-shim es5-shim/es5-sham babel-polyfill ./app/bundles/WalletApp/startup/registration

I add this on my react_on_rails gem for rails app

**Comment by mihaiblaga89** [comment]
same error here.

**Comment by srdjan** [comment]
which loader are you using? this component requires browserify installed

**Comment by korroktheslavemaster** [comment]
can't it work with webpack? I'm using create-react-app for setting up my react app which by default uses webpack

**Comment by srdjan** [comment]
it can, it is only the example that uses browserify...  component itself can be used in webpack projects

**Comment by korroktheslavemaster** [comment]
I think this is same as #20 , I'm using a custom solution for this too...

**Comment by asif-ir** [comment]
How to solve this? I'm stuck on a problem.

**Comment by srdjan** [comment]
@asif-ir, I just aded webpack build for the example... take a look it should be helpful

**Comment by Damilare1** [comment]
I'm try to use this package in my project but I keep getting similar error on build with Webpack.

ERROR in ../node_modules/react-multistep/src/index.js 37:8
[1] Module parse failed: Unexpected token (37:8)
[1] You may need an appropriate loader to handle this file type.
[1] |
[1] | export default class MultiStep extends React.Component {
[1] >   state = {
[1] |     showPreviousBtn: false,
[1] |     showNextBtn: true,

Please help
