### ISSUE TITLE
Validation for input forms

### ISSUE THREAD

**Issue by Dave-Algorism** [srdjan/react-multistep#32]
Hello, how can one add validation to the input forms? I want to prevent the next page from showing up if no data has been entered in the present page's input forms. Thank you

**Comment by nabrowning** [comment]
I would also really like to have the ability to validate forms /submit on hitting next.

**Comment by Pizdetss** [comment]
- add a valid state to the step
- when fields are entered set state as valid
- if not valid you can highlight field with message and hide/disable next button

**Comment by Dave-Algorism** [comment]
@Pizdetss :thumbs

**Comment by Dave-Algorism** [comment]
Hi @Pizdetss being trying to wrap my head around your suggestion which is the logical thing to do but it isn't working for me. Can you please help me out? Thanks in advance

**Comment by Pizdetss** [comment]
@Dave-Algorism sure thing, anywhere in particular you a stuck?

**Comment by Dave-Algorism** [comment]
@Pizdetss First, my case is somewhat different. I have loads of forms that I pull from the backend (dynamic forms), I sectioned them into components. Since the forms are dynamic i.e the name of the form fields changes, I might not be able to declare them in the state which means I have to validate the forms dynamically. Having said this, I tried putting "valid= false" in the parent component that holds the child components which contains sections holding and I tried setting "valid = true" as the form fields are being filled but I am not getting the result. This is where I am stuck

**Comment by Pizdetss** [comment]
@Dave-Algorism 
Sounds like you need to pass the valid state to the parent via callback. 

In you child component where you do the validation and set the valid=true state, something like this:
`setState({
    valid: true,
), this.props.callbackParent(this.state.valid)}`

Then in your parent component:

`<ChildComponent valid={this.state.valid} callbackParent={(component) => this.handCallback(component)} />`

And again the parent component create a method to handle the callback:
```
handleCallback(newState) {
 setState({
  valid: newState;
 })
}
```

**Comment by Dave-Algorism** [comment]
@Pizdetss
Wow! thank you for your prompt reply. Will give this a try and will let you know how far I have gone. I am grateful

**Comment by daveteu** [comment]
I am having the same scenario and I cannot figure out, is there a props that we can enable/disable the next button?

**Comment by srdjan** [comment]
no, bur you can contribute via PR? :)
