### ISSUE TITLE
Documentation to work with create-react-app?

### ISSUE THREAD

**Issue by prabshah** [srdjan/react-multistep#34]
Hi
First of all thank you for the great project. However I am trying to use it in my project (CRA) and I get the following:

```js
./node_modules/react-multistep/src/index.js
Module parse failed: Unexpected token (98:6)
You may need an appropriate loader to handle this file type.
|   renderSteps() {
|     return this.props.steps.map((s, i)=> (
|       <li className={this.getClassName("progtrckr", i)} onClick={this.handleOnClick} key={i} value={i}>
|         <em>{i+1}</em>
|         <span>{this.props.steps[i].name}</span>
```

any ideas? happy to contribute to the docs if you point me in the right direction.

Thanks

**Comment by srdjan** [comment]
just out of curiosity... what happens if you rename: 
./node_modules/react-multistep/src/index.js
t ./node_modules/react-multistep/src/index.jsx
?
