### ISSUE TITLE
npm test: showing the error as below

### ISSUE THREAD

**Issue by gogears** [srdjan/react-multistep#35]
E:\localstorage\react-multistep-master>npm test

> react-multistep@3.2.2 test E:\bitbucket\react-multistep-master
> todo... mocha

'todo...' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details

**Note:** I had tried to run "Dev Instructions", but it is showing the error as above. Help me out of this issue.
![wizard-npmtest-not-working](https://user-images.githubusercontent.com/6576486/42571813-b098e8b0-8535-11e8-9725-c0ebfb098f9b.PNG)

**Comment by srdjan** [comment]
I removed 'todo' comment - not sure why would that be a problem...
but, effectively there are no tests to run - that is why there was 'todo' in the first place :|
If you want to add some, please make a PR?
