### ISSUE TITLE
Data is not persistent across Steps

### ISSUE THREAD

**Issue by irobalino** [srdjan/react-multistep#37]
Hi @srdjan.  I noticed that state data is not been saved between steps. I know this works fine in your demo page but If follow these steps you will be able to see what I am talking about

- Clone this repo
- npm install
- npm run build
- upload build to a webserver

Do you have any idea what might be wrong?

Regards

Ivan

**Comment by srdjan** [comment]
this is the same as #36 - I encourage you to see the answer there, by @stevenmunro
essentially, you need external state, like has done:

"each component for StepOne, StepTwo, StepThree, and StepFour has its own state (this.state) that is wiped clean when the component is replaced by another.
I fixed this myself by declaring state on the app component, and passing functions via props to each of the (child component) steps."
