### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by sesanka** [srdjan/react-multistep#38]
./node_modules/react-multistep/src/index.js
Module parse failed: Unexpected token (37:8)
You may need an appropriate loader to handle this file type.
| 
| export default class MultiStep extends React.Component {
|   state = {
|     showPreviousBtn: false,
|     showNextBtn: true,

**Comment by srdjan** [comment]
what steps are you following?

did you run: 
`npm run build-with-webpack`?

**Comment by rebeccazeng** [comment]
From the package.json, the specification for build-with-webpack uses ./example/bundle.js, which I can't seem to find. Also, upon trying to use the script, the same error occurs

**Comment by srdjan** [comment]
./example/bundle.js is created once you run 

`npm run build-with-webpack`

so it will not be there before you do

**Comment by rebeccazeng** [comment]
I've copied the specifications for build-with-webpack and put that into my own package.json, but it doesn't seem to solve the issue; is there a step I'm missing?

**Comment by srdjan** [comment]
any chance you can share your project with me ?
Would like to help but need to see what is going on

**Comment by rebeccazeng** [comment]
Sure thing! I've sent you an email. Thanks for offering to help!

**Comment by rebeccazeng** [comment]
Fixed the issue! My issue was in my webpack.config.js file, and my boilerplate setup from another tutorial for setting up webpack didn't function as needed. I replaced the elements of my project with the running example's specifications, and it works!

**Comment by srdjan** [comment]
thanks for the note... I'll check that out
