### ISSUE TITLE
ERROR in ./node_modules/react-multistep/src/index.js 37:8

### ISSUE THREAD

**Issue by radman-x** [srdjan/react-multistep#41]
Getting this error when including react-multistep in my webpack project:

  Windows 10
  Webpack 4.28.3
  React 16.7

Steps to repo (in a react project with above Webpack version, running Webpack dev-server):

   * npm i react-multistep --save
   * In a JSX file add the following line:
         `import MultiStep from 'react-multistep/src/index';`
   * Wait for dev-server to compile, but it fails with this error:

```
ERROR in ./node_modules/react-multistep/src/index.js 37:8
Module parse failed: Unexpected token (37:8)
You may need an appropriate loader to handle this file type.
|
| export default class MultiStep extends React.Component {
>   state = {
|     showPreviousBtn: false,
|     showNextBtn: true,

```

Tried going into the node_modules/react-multistep file and do the "npm run build-with-webpack" you suggested in some other issues (but seems like this just builds the sample app and has nothing to do with using the node module in a real project) and it gave a similar error.

Seems like this issue is similar to #38, #30, #23, #20, none of which were solved in a general way.

**Comment by srdjan** [comment]
fixed
