### ISSUE TITLE
Failed to compile on fresh install

### ISSUE THREAD

**Issue by sol-idsnake** [srdjan/react-multistep#42]
With create-react-app, I installed via `npm install react-multistep`. Then, following the directions provided in the readme I get the following error: 

`./node_modules/react-multistep/src/index.js
SyntaxError: ...\node_modules\react-multistep\src\index.js: Unexpected token (63:6)

  61 |   const renderSteps = () => 
  62 |     props.steps.map((s, i) => (
> 63 |       <li
        |       ^
  64 |         className={'progtrckr-' + stylesState[i]}
  65 |         onClick={handleOnClick}
  66 |         key={i}`

**Comment by tknott1** [comment]
I'm on windows 10, using NPM instal react-multistep I recieved this error. By copying the script and including it locally it seems to solve this issue

**Comment by srdjan** [comment]
hmm... which script did you copy locally?

**Comment by tknott1** [comment]
https://github.com/srdjan/react-multistep/blob/master/src/index.js
Is the file that I pulled down locally, it worked without any modifications then.

I went ahead and swapped from this library to react-stepzilla after that though. Funny enough, the react-stepzilla npm install worked like a charm, and the syntax was identical

**Comment by srdjan** [comment]
it is cool - it is the same syntax because author of that project has copied from this one ;) 
he continued to maintain it actively and add more features... so, you are better off (probably)

@sol-idsnake, I'll try to reproduce and fix this weekend

**Comment by srdjan** [comment]
aded better instructions to the readme file

**Comment by sankalp-jain** [comment]
> I'm on windows 10, using NPM install react-multistep I recieved this error. By copying the script and including it locally it seems to solve this issue

I tried the same thing it didn't work for me...Can you please elaborate the steps
