### ISSUE TITLE
Npm install won't work correctly and repeats on fresh installs

### ISSUE THREAD

**Issue by Dmitry-Sokolov** [srdjan/react-multistep#43]
ERROR in ./node_modules/react-multistep/index.js 65:6
Module parse failed: Unexpected token (65:6)
You may need an appropriate loader to handle this file type.
|   const renderSteps = () => 
|     props.steps.map((s, i) => (
>       <li
|         className={'progtrckr-' + stylesState[i]}
|         onClick={handleOnClick}

For correct work used https://github.com/newbreedofgeek/react-stepzilla
this install works without problem

**Comment by UtkarshVIT** [comment]
Getting the same error. Any workaround for this?

**Comment by srdjan** [comment]
can you provide more information, please? what are the commands/steps that led to this error?

**Comment by mohammadaminazimi** [comment]
Same Error!!!!!!!!!!!!!!!!!!
