### ISSUE TITLE
React MultiSelect button class

### ISSUE THREAD

**Issue by RahulShahUI** [srdjan/react-multistep#47]
how to add class in action buttons

**Comment by srdjan** [comment]
not enough information given.... not sure what are you trying to do...
closing

**Comment by RahulShahUI** [comment]
> not enough information given.... not sure what are you trying to do...
> closing

I have attached one screenshot and i want to add some class in highlighted next button. 

<img width="555" alt="rct-img" src="https://user-images.githubusercontent.com/38944466/61766341-2d034c00-adfe-11e9-8224-f84217a286b9.png">
