### ISSUE TITLE
How to className to container and Previous, Next buttons

### ISSUE THREAD

**Issue by suhailkc** [srdjan/react-multistep#51]
I want to style using the parent class.

ie, I want to use like this:
`<MultiStep showNavigation={true} className="my-class" steps={steps}/>`
 But `className` not working.

Is there any way to give `className` to the container???

Also, I want to add `className` to `Previous` and `Next` buttons for styling.

I'm waiting for your reply.

**Comment by pradeep-kooky** [comment]
You can give class in index,js(react-multistep) like this:
eg:
return React.createElement("div", {
    className: "container my-class",
    style: { backgroundColor: "#f4f4f4", paddingTop: '50px' }, 
    onKeyDown: handleKeyDown
  }

**Comment by jpcmf** [comment]
@pradeep-kooky how add className to the buttons?

**Comment by EsioFreitas** [comment]
@srdjan help us!

**Comment by srdjan** [comment]
just published new version - check it and let me know
