### ISSUE TITLE
Problem running example

### ISSUE THREAD

**Issue by yarivShamash** [srdjan/react-multistep#54]
Hey,

I'm trying to learn your repo using the example but encoutered problems with the last two steps.
On `react-multistep/example` when running `sudo npm run build:dev` I receive the following error:
```
npm ERR! missing script: build:dev
```
any thoughts on how and why can it happen?

**Comment by kashammari** [comment]
It's in the package.json in the src folder!

**Comment by kashammari** [comment]
I get this node module error so I gave up on it!
./src/node_modules/react/cjs/react.development.js
  Line 632:60:  Definition for rule 'react-internal/warning-and-invariant-args' was not found

**Comment by yarivShamash** [comment]
Thanks, I'll look into it.

**Comment by srdjan** [comment]
should be fixed now... on master - not on NPM yet

**Comment by nuritb** [comment]
I love your repo! but I also get this error:

./src/node_modules/react/cjs/react.development.js
Line 632:60: Definition for rule 'react-internal/warning-and-invariant-args' was not found.

Is there any solution?

**Comment by srdjan** [comment]
can't reproduce...
are you using the module from NPM or have cloned/forked the repo?
