### ISSUE TITLE
Passing props to steps

### ISSUE THREAD

**Issue by yarivShamash** [srdjan/react-multistep#55]
I am incorporating your library in a project I'm doing. In this project I am converting a one-pager for into a multi-step form. The `<MultiStep />` component is rendered by another component which should pass `props` to the slides. I tried to pass it through `<MultiStep steps={steps} user={user} />` but `user` didn't pass to the steps.
I couldn't find a documentation that explains how to do it.

Would appreciate your help on this subject :)

**Comment by anggaand123** [comment]
i implement steps data in state
incase new props coming or change use componentWillReceiveProps instead

**Comment by yarivShamash** [comment]
Thanks :)

**Comment by srdjan** [comment]
thanks @anggaand123 !
