### ISSUE TITLE
Next button is not showing up if number of props.steps increased during multistep lifecycle

### ISSUE THREAD

**Issue by BondoS** [srdjan/react-multistep#58]
My case: 
I have 3 steps, if the third step is valid, I'll send the fourth step to props.steps of multistep component and if the fourth is valid, I'll send the fifth step to multistep and so forth until I finish my scenario journey.

The issue:
Steps: 
- If we just have three steps and I am already in the third one.
- After some user inputs, the third step got valid.
- My code automatically sends the fourth step to the multistep component.
- The nav styles get updated, but the buttons still as is, with NO next button visible.

Why: 
Because updating the buttons only happens on three events
When the user hits
1- The navigation list items
2- Next button
3- Previous button

The fix:
- Buttons should be updated on props.steps changes 

I have created a pull-request with the fix
https://github.com/srdjan/react-multistep/pull/57

Thank you

**Comment by srdjan** [comment]
merged!
thank you
