### ISSUE TITLE
module css overrides html elements

### ISSUE THREAD

**Issue by ertemishakk** [srdjan/react-multistep#63]
npm module applies css styling to specific html tags which can not be removed or overwritten. For example list items.

**Comment by srdjan** [comment]
yes, currently it doesn't support independent styling.
I have a working version that does, though - will publish soon

**Comment by mpukit** [comment]
Also seeing that other `<li>` item styles are getting overridden by this components styles. Any chance the styling can be made specific to this component and styles more easily editable (maybe even including a prop for custom class names)?

**Comment by srdjan** [comment]
yes, it is already done - just don't have time, at the moment to polish and push... 
few days out, max.

**Comment by srdjan** [comment]
latest release should fix these issues.
let me know if you still have the same problem

**Comment by srdjan** [comment]
ok, cool - closing!
