### ISSUE TITLE
Issue on npm run build

### ISSUE THREAD

**Issue by amolksagar** [srdjan/react-multistep#67]
Hi,

When I execute the command **npm run build** after executing **npm install** I get the below mentioned error

**error: Must use "outdir" when there are multiple input files**

FYI: I have checked out the master

**Comment by srdjan** [comment]
cannot reproduce...
I just made a fresh clone of the repo, ran 'npm i' and than 'npm run build' -> no error

this  esbuild error could appear if there are multiple entry points... can you provide your package.json?

**Comment by amolksagar** [comment]
{
  "name": "react-multistep",
  "version": "5.1.1",
  "description": "Responsive ReactJS multistep form component",
  "main": "index.umd.js",
  "module": "index.esm.js",
  "license": "MIT",
  "author": {
    "name": "@djidja8",
    "email": "srdjan@timok.com",
    "url": "https://github.com/srdjan"
  },
  "keywords": [
    "react, reactjs, responsive, component"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/srdjan/react-multistep"
  },
  "homepage": "https://github.com/srdjan/react-multistep",
  "bugs": {
    "url": "https://github.com/srdjan/react-multistep/issues"
  },
  "dependencies": {
    "goober": "2.0.10"
  },
  "devDependencies": {
    "csstype": "3.0.4",
    "esbuild": "0.7.19",
    "react": "17.0.1",
    "node-forge": ">=0.10.0"
  },
  "peerDependencies": {
    "react": "17.0.1"
  },
  "scripts": {
    "build": "esbuild react-multistep.js '--define:process.env.NODE_ENV=\"development\"' --external:'react' --bundle --format=cjs --loader:.js=jsx --outfile=index.tar",
    "build:prod": "esbuild react-multistep.js '--define:process.env.NODE_ENV=\"production\"' --external:'react' --bundle --minify --format=cjs --loader:.js=jsx --outfile=index.js",
    "pub:dry": "npm publish ./ --dry-run",
    "pub": "npm publish ./"
  }
}

**Comment by srdjan** [comment]
do you maybe have different esbuild version installed globally?

**Comment by amolksagar** [comment]
In fact I do not have esbuild itself. Is that the issue? Below is what happens when I do esbuild from git bash
. Do i need it like npm? But then it should have complained about esbuild command not found.Sorry I am new to UI development. Is my understanding correct?

$ esbuild
bash: esbuild: command not found

**Comment by srdjan** [comment]
hmm, try 
`npx esbuild`

**Comment by amolksagar** [comment]
$ npx esbuild --version
0.8.9

**Comment by srdjan** [comment]
that is different than what (current) package.json installs ("esbuild": "0.7.19",)
upgraded myself, but still no issues on my side. 
Are you on Windows?

**Comment by amolksagar** [comment]
thats right.I am on windows. I have tried both the build and prod:build commands

**Comment by srdjan** [comment]
ah...
so, this is a bug (I believe) in esbuild and it manifests on Windows only. Comes from this file:

<img width="751" alt="Screen Shot 2020-11-19 at 5 00 13 PM" src="https://user-images.githubusercontent.com/61190/99729648-3996c380-2a89-11eb-844c-22ea55853d24.png">

I don't have a Windows machine to reproduce, so I can't open a new issue there, but you can - if you want...
