### ISSUE TITLE
Step name is not displayed

### ISSUE THREAD

**Issue by r3dge** [srdjan/react-multistep#71]
The name of each step is not displayed. We can only see the number of the step (1,2,3,4 etc..)

I guess you should fix it by changing line 123 (react-multistep.js) `<span>{i+1}</span>` by `<span>s</span>`

**Comment by srdjan** [comment]
thanks for reporting - I'll take a look...

**Comment by Stuartkal** [comment]
hello, have you pushed any updates on this?

**Comment by srdjan** [comment]
no, wanted to address responsiveness (name shouldn't show in mobile mode), but didn't have time yet...
PR welcome! :)
