### ISSUE TITLE
Breaking onKeyDown behaviour

### ISSUE THREAD

**Issue by daweimau** [srdjan/react-multistep#74]
https://github.com/srdjan/react-multistep/blob/acb2b64e1db9d6d4410e399b6df8336251786006/src/index.js#L141

This line and function seems to be trying to allow user to progress to next step by pressing the return key.  Currently this does not work.

However if the user has a modal open inside a step (for example they are completing a form inside a modal) then the return button now moves the user to the next step (and exits the modal and form entirely).

Can solve by removing onKeyDown entirely, since its intended purpose is not working and it is just introducing breakages.

**Comment by srdjan** [comment]
please open a PR?
