### ISSUE TITLE
Story: Add Typescript definitions

### ISSUE THREAD

**Issue by EgeOnder** [srdjan/react-multistep#80]
`Could not find a declaration file for module 'react-multistep'.`

Would be nice if there was @types/react-multistep library or built-in inside this one. Cannot use it with Typescript, unfortunately.

**Comment by jrnkng** [comment]
Is this still the case? Huge bummer if so :(

**Comment by srdjan** [comment]
Re-opening this issue, will add in the next version

**Comment by srdjan** [comment]
thanks @ofirelarat !
