### ISSUE TITLE
Step name not shown

### ISSUE THREAD

**Issue by skydavis** [srdjan/react-multistep#81]
Currently, step names are not shown. (You can only see the number, 1,2,3,etc). Is this expected behavior?

**Comment by nasirzid** [comment]
how can I trigger click event on click of next and previous buttons?

**Comment by joelRhibhus** [comment]
Hi @srdjan,  can you please add the name instead of i2 + 1 in dist/index.js? It worked for me.

**Comment by srdjan** [comment]
if I remember correctly, there is a bit more to it, to make it look good on smaller screens...

**Comment by DillonZip** [comment]
Bumping this. Still looks to be an issue

**Comment by srdjan** [comment]
if anybody has done this and test it - please open a PR
otherwise, I'll get to it, it needs to be done, just don't have time right now

**Comment by ofirelarat** [comment]
> if anybody has done this and test it - please open a PR otherwise, I'll get to it, it needs to be done, just don't have time right now

I tested it, and its look fine in mobile look as well, I opened PR you can check it out

**Comment by srdjan** [comment]
thanks @ofirelarat !
