### ISSUE TITLE
on click next and previous

### ISSUE THREAD

**Issue by nasirzid** [srdjan/react-multistep#83]
how can I trigger click event on click of next and previous buttons?

**Comment by jsxNeko** [comment]
I am also curious about this. Especially for validating before moving to the next step.

**Comment by srdjan** [comment]
yes, that would be a good feature, that is why I keep the issue open... 
plan to work on that as soon as I get time to do it. 

If you are willing to give it a shot, PR is welcome 🤗 ..
The approach would be to pass a callback to child components and have them signal 'disable | enable' events...
react-multistep would than flip 'disable' attribute and change style on the 'prev' or 'next' button, something like this:
```
  const handleChildEvent = evt => { 
    if( evt.currentTarget.value === 'prev') {
       const prevButton = document.getElementById('prev')
       prevButton.setAttribute('disabled', !(prevButton.getAttribute('disabled'))
       prevButton.style.background = 'gray'
    } else if( evt.currentTarget.value === 'next') {
     ...
    }
  }

```

**Comment by srdjan** [comment]
here is a little bit more sketched approach:
`
import React, { useState, useEffect } from 'react';

const Parent = props => {
  const [isInvalid, setIsInvalid] = useState(true)
  
  props.children[0].component.props.onValidation.handler = () => setIsInvalid(isInvalid => !isInvalid)

  useEffect(() => {
    console.log(`isInvalid state: ${isInvalid}`)
  }, [isInvalid])

  return (
    <div className='parent'>
      <h1>Hello from Parent.</h1>
      <div> {`Component is in valid state?: ${!isInvalid}`}</div>
      <div>{props.children[0].component}</div>
      <button id='prev' className='prev'>Prev</button>
      <button id='next' className='next' disabled={isInvalid}>Next</button>
    </div>
  )
}

const Child1 = props => (
  <div className='child'>
    <h3>Hello From Child, <span onClick={props.onValidation.handler}>Click me!</span></h3>
  </div>
)

const Child2 = props => (
  <div className='child'>
    <div>
      <h2>Hello From Child, NO Validation</h2>
    </div>
  </div>
)

//--  application --
const children = [
  { component: <Child1 name={'First'} onValidation={{ handler: null }} /> },
  { component: <Child2 name={'Second'}  /> }
]

const App = (props) => {  
  return (  
    <Parent children={children} />
  )
}

export default App
`
@ofirelarat what do you think?

**Comment by srdjan** [comment]
so...
If the Child component has `onValidation={{ handler: null }}` prop defined, 'next' nav button would be disabled until Child signals validation change. Not trivial, but not too difficult, too...
If nobody picks this up, I'll get back to it next weekend hopefully...

**Comment by DillonZip** [comment]
Just adding my voice that I would really like this feature to be added

**Comment by srdjan** [comment]
will try to get this done as soon as I get some free time

**Comment by srdjan** [comment]
Thank you all.
Created a story (#98) for this. Will try to implement over the Holidays.
Closing this one, please track progress over at #98
