### ISSUE TITLE
the list of Name is not working 

### ISSUE THREAD

**Issue by kuldeepgaharwars** [srdjan/react-multistep#84]
![image](https://user-images.githubusercontent.com/18482412/184075036-1e1ec7ac-e7c8-4501-84d6-786375b63a72.png)

**Comment by kuldeepgaharwars** [comment]
Out put is-
![image](https://user-images.githubusercontent.com/18482412/184075211-e838245b-ac15-4754-8cda-3d9414342905.png)

**Comment by srdjan** [comment]
duplicate with #81
