### ISSUE TITLE
'Prev' button showing on first page

### ISSUE THREAD

**Issue by DillonZip** [srdjan/react-multistep#86]
When loading the first step of the form the 'Prev' button shows rather than 'Next'. I have to click it before it will change to display the 'Next' button

**Comment by srdjan** [comment]
Hmmm, I cannot reproduce that behavior

**Comment by DillonZip** [comment]
Thanks for the response. 
I ended up closing it because I realized that on a different computer when I ran the project locally the button behavior worked and the progress bar would work. But on my other computer and when I push it to my s3 bucket for hosting it doesn't work. So it seems environmental... I'm not sure how to get it working correctly unfortunately. I don't know if it's related to this or not, but VS code does complain about my import 

import MultiStep from 'react-multistep';

Could not find a declaration file for module 'react-multistep'. '<myProjectPath>/node_modules/react-multistep/index.js' implicitly has an 'any' type.

Seems to be a "me" issue though lol. If you have any thoughts that would be awesome, but I'll keep playing with it to see if I can sort it out.

**Comment by srdjan** [comment]
ok, hard to say without having access to the code that you have. 

But, you can check the answer here:
https://stackoverflow.com/questions/47848778/parameter-implicitly-has-an-any-type
It may be of help - this is a js component, which should work in a TypeScript project, but ...
