### ISSUE TITLE
Hard dependency on jsx

### ISSUE THREAD

**Issue by Morriz** [Srdjan/react-multistep#9]
Hi, your module throws errors on the jsx in line 53 of index.js. The jsx which should not be in your published module.

Please always export your code without any dependencies on es6 or jsx, so other people can include it as is.

Thanks in advance!

**Comment by Srdjan** [comment]
done

**Comment by Morriz** [comment]
Sorry dude. My bad. It was fine in github, just wanted to include it as an npm module, which you didn't publish. So I tried referencing it in my package.json the github way, which blew up. 

It would be nice ig you could just build your artefacts and publish them as an npm module. The src was fine as is...my bad

**Comment by Srdjan** [comment]
yes, I'm planning to do that - wanted to add some tests and a little usability enhancement first... 
v2.0 should be on npm by tomorrow EOD
