### ISSUE TITLE
Build 5.3.1 Error

### ISSUE THREAD

**Issue by DillonZip** [srdjan/react-multistep#91]
This build is broken for me. Is anyone else having issues?

It's throwing an error and failing to render the page -
"Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component."

I can however run the storybook just fine though, so not sure what the issue is here. Any help is appreciated

**Comment by ofirelarat** [comment]
and in the version before 5.3.0 its works fine to you?
I will try check it also by the way

**Comment by ofirelarat** [comment]
I opened PR that supposed to fix it #92 
you can check it in the PR branch as well

**Comment by srdjan** [comment]
works for me now... will re-open if needed
