### ISSUE TITLE
Remove Storybook, WebPack....

### ISSUE THREAD

**Issue by srdjan** [srdjan/react-multistep#94]
cc @ofirelarat 

lets keep StoryBook in an external repo/setup. It is a huge dependency (brings in WebPack and friends...) and raises maintenance efforts. Security warnings are already coming in:
<img width="478" alt="Screenshot 2022-11-16 at 5 45 48 AM" src="https://user-images.githubusercontent.com/61190/202160389-c261ca3d-cac5-4062-b6d6-b4eda2f56379.png">

**Comment by ofirelarat** [comment]
You are right, I will create PR for this ASAP

**Comment by srdjan** [comment]
thank you !

**Comment by srdjan** [comment]
merged - thanks!
